// 面试/07. 表单数据同步与保持/课堂代码/vue-form-storage/src/views/Page1.vue
<template>
  <div class="container">
    <h1>问题页1</h1>
    <form id="page1Form">
      <div>
        <label for="question1">您的姓名：</label>
        <input
          v-model="formData.username"
          type="text"
          name="question1"
          placeholder="请填写您的姓名"
        />
      </div>
      <div>
        <label for="question2">您的性别：</label>
        <select name="question2" v-model="formData.gender">
          <option value="male">男</option>
          <option value="female">女</option>
          <option value="secret">保密</option>
        </select>
      </div>
      <button class="single" @click.prevent="nextPage">下一页</button>
    </form>
  </div>
</template>

<script setup>
import { ref, onMounted, watch } from 'vue'
import { useRouter } from 'vue-router'
import FormStorage from '../utils/FormStorage'

const formData = ref({
  username: '',
  gender: 'secret'
})
const formStorage = new FormStorage('page1Form', formData)

onMounted(() => {
  console.log('mounted1')
  formStorage.init()
})

watch(
  formData,
  () => {
    formStorage.debouncedSaveData() // 使用防抖保存数据
  },
  { deep: true }
)

const router = useRouter()
const nextPage = () => {
  // 切换路由之前先保存一下数据
  formStorage.saveData()
  router.push('/page2')
}
</script>

<style scoped>
.button-group {
  display: flex;
  justify-content: space-between;
}
</style>

// 面试/07. 表单数据同步与保持/课堂代码/react-form-storage/src/views/Page1.jsx
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import useFormStorage from "../hooks/useFormStorage";

const Page1 = () => {
  const [formData, setFormData] = useState({
    username: "",
    gender: "secret",
  });
  const navigate = useNavigate();

  const formStorage = useFormStorage("page1Form", formData, setFormData);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prevData) => ({
      ...prevData,
      [name]: value,
    }));
  };

  const nextPage = () => {
    formStorage.saveData();
    navigate("/page2");
  };

  return (
    <div className="container">
      <h1>问题页1</h1>
      <form id="page1Form">
        <div>
          <label htmlFor="username">您的姓名：</label>
          <input
            name="username"
            type="text"
            value={formData.username}
            onChange={handleChange}
            placeholder="请填写您的姓名"
          />
        </div>
        <div>
          <label htmlFor="gender">您的性别：</label>
          <select name="gender" value={formData.gender} onChange={handleChange}>
            <option value="male">男</option>
            <option value="female">女</option>
            <option value="secret">保密</option>
          </select>
        </div>
        <button className="single" type="button" onClick={nextPage}>
          下一页
        </button>
      </form>
    </div>
  );
};

export default Page1;
